service:
  name: scaleway-golang

provider:
  name: scaleway
  runtime: golang
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: <scw-token>
  scwOrganization: <scw-organization-id>

plugins:
  - serverless-scaleway-functions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    # If handler is at the root of your serverless project
    handler: "."
    # Local environment variables - used only in given function
    env:
      local: local

  mypackage:
    # if your handler is in a custom package
    handler: mypackage
