service:
  name: scaleway-typescript

provider:
  name: scaleway
  runtime: node10
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: <scw-token>
  scwOrganization: <scw-organization-id>

plugins:
  - serverless-webpack
  - serverless-scaleway-functions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  first:
    # Path to compiled JavaScript Handler
    # Note that this must be a `.js` file even though you are using .ts
    handler: src/handler.js
    # Local environment variables - used only in given function
    env:
      local: local
